export interface Product {
  slug: string
  name: string
  price: number
  unit: string
  category: "fresh-produce" | "meat-seafood" | "oils-cooking" | "rice-grains" | "pantry-packaged" | "spices-seasoning"
  subcategory?: string
  featured: boolean
  image: string
  fallback: string
  description: string
  metaTitle: string
  metaDescription: string
}

export const allProducts: Product[] = [
  { slug: "yam", name: "Yam", price: 2.99, unit: "per lb", category: "fresh-produce", featured: true, image: "/images/yam.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh African yam, a hearty root vegetable perfect for boiling, frying, or pounding into fufu. A true West African staple.", metaTitle: "Fresh Yam - Adom African Market Minneapolis", metaDescription: "Buy fresh African yam at Adom African Market in Minneapolis. Perfect for boiling, frying, or pounding. $2.99 per lb." },
  { slug: "yellow-plantain", name: "Yellow Plantain", price: 1.29, unit: "per lb", category: "fresh-produce", featured: true, image: "/images/plantain.jpg", fallback: "https://placehold.co/400x300/png", description: "Ripe yellow plantains, sweet and ready for frying, baking, or grilling. A staple in African and Caribbean cuisine.", metaTitle: "Yellow Plantain - Adom African Market Minneapolis", metaDescription: "Buy ripe yellow plantains at Adom African Market in Minneapolis. Sweet and perfect for frying, baking, or grilling. $1.29 per lb." },
  { slug: "green-plantain", name: "Green Plantain", price: 1.59, unit: "per lb", category: "fresh-produce", featured: true, image: "/images/plantain.jpg", fallback: "https://placehold.co/400x300/png", description: "Firm green plantains ideal for boiling, frying into chips, or making fufu. A versatile cooking staple.", metaTitle: "Green Plantain - Adom African Market Minneapolis", metaDescription: "Buy green plantains at Adom African Market in Minneapolis. Ideal for boiling, chips, or fufu. $1.59 per lb." },
  { slug: "fufu", name: "Fufu", price: 6.99, unit: "bag", category: "fresh-produce", featured: true, image: "/images/fufu.jpg", fallback: "https://placehold.co/400x300/png", description: "Ready-to-prepare fufu, the classic West African side dish. Made from pounded starchy vegetables, perfect with soups and stews.", metaTitle: "Fufu - Adom African Market Minneapolis", metaDescription: "Buy fufu at Adom African Market in Minneapolis. Classic West African side dish for soups and stews. $6.99 per bag." },
  { slug: "cassava-leaf", name: "Cassava Leaf", price: 4.99, unit: "bunch", category: "fresh-produce", featured: false, image: "/images/cassava.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh cassava leaves, a staple green in West and Central African cooking. Rich in nutrients and perfect for traditional stews.", metaTitle: "Cassava Leaf - Adom African Market Minneapolis", metaDescription: "Buy fresh cassava leaf at Adom African Market in Minneapolis. Nutrient-rich greens for traditional stews. $4.99 per bunch." },
  { slug: "fresh-peanuts", name: "Fresh Peanuts", price: 4.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/peanuts.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh raw peanuts, also known as groundnuts. Essential for African soups, sauces, snacking, and making groundnut paste.", metaTitle: "Fresh Peanuts - Adom African Market Minneapolis", metaDescription: "Buy fresh peanuts (groundnuts) at Adom African Market in Minneapolis. For soups, sauces, and snacking. $4.99 per lb." },
  { slug: "sweet-potato", name: "Sweet Potato", price: 2.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/yam.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh sweet potatoes with a naturally sweet, creamy flesh. Great for roasting, boiling, or making porridge.", metaTitle: "Sweet Potato - Adom African Market Minneapolis", metaDescription: "Buy fresh sweet potatoes at Adom African Market in Minneapolis. Naturally sweet and creamy. $2.99 per lb." },
  { slug: "fresh-okra", name: "Fresh Okra", price: 4.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/okro.jpg", fallback: "https://placehold.co/400x300/png", description: "Farm-fresh okra, perfect for soups, stews, and traditional West African dishes. Hand-selected for quality and freshness.", metaTitle: "Fresh Okra - Adom African Market Minneapolis", metaDescription: "Buy fresh okra at Adom African Market in Minneapolis. Perfect for soups, stews, and traditional dishes. $4.99 per lb." },
  { slug: "ginger", name: "Ginger", price: 3.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/ginger.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh ginger root with a bold, spicy flavor. Essential for teas, marinades, stews, and traditional remedies.", metaTitle: "Fresh Ginger - Adom African Market Minneapolis", metaDescription: "Buy fresh ginger root at Adom African Market in Minneapolis. Bold flavor for teas, marinades, and stews. $3.99 per lb." },
  { slug: "coco-yam", name: "Coco Yam", price: 2.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/yam.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh coco yam, a starchy root vegetable perfect for boiling, porridges, and thickening soups.", metaTitle: "Coco Yam - Adom African Market Minneapolis", metaDescription: "Buy fresh coco yam at Adom African Market in Minneapolis. Perfect for boiling, porridges, and thickening soups. $2.99 per lb." },
  { slug: "yellow-onion", name: "Yellow Onion", price: 0.89, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/onion.jpg", fallback: "https://placehold.co/400x300/png", description: "Everyday yellow onions, the foundation of countless African dishes. Sweet when cooked, sharp when raw.", metaTitle: "Yellow Onion - Adom African Market Minneapolis", metaDescription: "Buy yellow onions at Adom African Market in Minneapolis. A kitchen essential for African cooking. $0.89 per lb." },
  { slug: "frozen-plantain", name: "Frozen Plantain", price: 6.49, unit: "each", category: "fresh-produce", featured: false, image: "/images/plantain.jpg", fallback: "https://placehold.co/400x300/png", description: "Frozen plantain, pre-cut and ready to fry or bake. A convenient way to enjoy plantain any time.", metaTitle: "Frozen Plantain - Adom African Market Minneapolis", metaDescription: "Buy frozen plantain at Adom African Market in Minneapolis. Pre-cut and ready to fry or bake. $6.49 each." },
  { slug: "cassava", name: "Cassava", price: 1.99, unit: "each", category: "fresh-produce", featured: false, image: "/images/cassava.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh cassava root, a versatile staple used for fufu, garri, tapioca, and many traditional African dishes.", metaTitle: "Fresh Cassava - Adom African Market Minneapolis", metaDescription: "Buy fresh cassava root at Adom African Market in Minneapolis. Versatile staple for fufu, garri, and more. $1.99 each." },
  { slug: "cassava-leaf-sierra-leone", name: "Cassava Leaf (Sierra Leone)", price: 5.99, unit: "pack", category: "fresh-produce", featured: false, image: "/images/cassava.jpg", fallback: "https://placehold.co/400x300/png", description: "Cassava leaf from Sierra Leone, a staple green used in traditional Sierra Leonean stews and sauces. Rich in nutrients.", metaTitle: "Cassava Leaf (Sierra Leone) - Adom African Market Minneapolis", metaDescription: "Buy Sierra Leonean cassava leaf at Adom African Market in Minneapolis. For traditional stews and sauces. $5.99." },
  { slug: "cassava-leaf-cameroon", name: "Cassava Leaf (Cameroon)", price: 7.99, unit: "pack", category: "fresh-produce", featured: false, image: "/images/cassava.jpg", fallback: "https://placehold.co/400x300/png", description: "Cassava leaf from Cameroon, perfect for traditional Cameroonian dishes and stews. Premium quality leaves.", metaTitle: "Cassava Leaf (Cameroon) - Adom African Market Minneapolis", metaDescription: "Buy Cameroonian cassava leaf at Adom African Market in Minneapolis. Premium leaves for traditional dishes. $7.99." },
  { slug: "garden-egg", name: "Garden Egg", price: 4.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/garden-egg.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh garden eggs, a small African eggplant used in stews, salads, and as a side dish. Mildly bitter and nutritious.", metaTitle: "Garden Egg - Adom African Market Minneapolis", metaDescription: "Buy fresh garden eggs at Adom African Market in Minneapolis. African eggplant for stews and salads. $4.99 per lb." },
  { slug: "onions-bulk", name: "Onions (Bulk)", price: 2.99, unit: "per lb", category: "fresh-produce", featured: false, image: "/images/onion.jpg", fallback: "https://placehold.co/400x300/png", description: "Bulk onions at a great value. Perfect for restaurants, large families, or anyone who cooks African dishes regularly.", metaTitle: "Bulk Onions - Adom African Market Minneapolis", metaDescription: "Buy bulk onions at Adom African Market in Minneapolis. Great value for large quantities. $2.99 per lb." },

  { slug: "tilapia", name: "Tilapia", price: 3.50, unit: "per lb", category: "meat-seafood", featured: true, image: "/images/tilapia.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh tilapia, a mild and versatile white fish. Excellent fried, grilled, or in light soups and stews.", metaTitle: "Fresh Tilapia - Adom African Market Minneapolis", metaDescription: "Buy fresh tilapia at Adom African Market in Minneapolis. Mild, versatile white fish for frying or grilling. $3.50 per lb." },
  { slug: "croaker-fish", name: "Croaker Fish", price: 4.99, unit: "per lb", category: "meat-seafood", featured: true, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh croaker fish with a delicate, sweet flavor. Popular in West African soups, stews, and fried dishes.", metaTitle: "Croaker Fish - Adom African Market Minneapolis", metaDescription: "Buy fresh croaker fish at Adom African Market in Minneapolis. Delicate flavor for soups and frying. $4.99 per lb." },
  { slug: "red-snapper", name: "Red Snapper", price: 9.99, unit: "per lb", category: "meat-seafood", featured: true, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh whole red snapper, a prized fish in West African cuisine. Perfect for grilling, frying, or pepper soup.", metaTitle: "Fresh Red Snapper - Adom African Market Minneapolis", metaDescription: "Buy fresh red snapper at Adom African Market in Minneapolis. Perfect for grilling, frying, or pepper soup. $9.99 per lb." },
  { slug: "goat-meat-cube", name: "Goat Meat Cube", price: 17.99, unit: "each", category: "meat-seafood", featured: true, image: "/images/goat.jpg", fallback: "https://placehold.co/400x300/png", description: "Premium goat meat cubes, pre-cut and ready for cooking. Perfect for stews, soups, and grilled dishes.", metaTitle: "Goat Meat Cube - Adom African Market Minneapolis", metaDescription: "Buy goat meat cubes at Adom African Market in Minneapolis. Pre-cut for stews, soups, and grilling. $17.99." },
  { slug: "golden-pompano", name: "Golden Pompano", price: 4.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/pompano.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh golden pompano, a mild and buttery fish prized in African and Asian cuisine. Excellent grilled, fried, or steamed.", metaTitle: "Golden Pompano - Adom African Market Minneapolis", metaDescription: "Buy fresh golden pompano at Adom African Market in Minneapolis. Mild, buttery fish for grilling or frying. $4.99 per lb." },
  { slug: "fresh-shrimp", name: "Fresh Shrimp", price: 16.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/shrimp.jpg", fallback: "https://placehold.co/400x300/png", description: "Premium fresh shrimp, perfect for jollof rice, stir-fry, soups, and seafood platters.", metaTitle: "Fresh Shrimp - Adom African Market Minneapolis", metaDescription: "Buy premium fresh shrimp at Adom African Market in Minneapolis. Great for jollof rice and seafood dishes. $16.99 per lb." },
  { slug: "mackerel-fish", name: "Mackerel Fish", price: 5.99, unit: "each", category: "meat-seafood", featured: false, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Whole mackerel fish, rich in omega-3 and full of flavor. Great for grilling, smoking, or frying.", metaTitle: "Mackerel Fish - Adom African Market Minneapolis", metaDescription: "Buy mackerel fish at Adom African Market in Minneapolis. Rich in omega-3, great for grilling or frying. $5.99." },
  { slug: "dry-fish", name: "Dry Fish", price: 8.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Traditional dried fish, a key ingredient in African soups and stews. Adds deep, rich umami flavor.", metaTitle: "Dry Fish - Adom African Market Minneapolis", metaDescription: "Buy dry fish at Adom African Market in Minneapolis. Essential for African soups and stews. $8.99 per lb." },
  { slug: "dry-smoked-fish", name: "Dry Smoked Fish", price: 8.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Premium dry smoked fish with a rich, smoky flavor. A must-have for authentic African stews and soups. Price ranges $8.99-$10.99 per lb.", metaTitle: "Dry Smoked Fish - Adom African Market Minneapolis", metaDescription: "Buy dry smoked fish at Adom African Market in Minneapolis. Rich smoky flavor for stews and soups. $8.99-$10.99 per lb." },
  { slug: "frozen-snails", name: "Frozen Snails", price: 15.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Frozen snails, a delicacy in West African cuisine. Perfect for pepper soup, stews, and grilled snail dishes.", metaTitle: "Frozen Snails - Adom African Market Minneapolis", metaDescription: "Buy frozen snails at Adom African Market in Minneapolis. West African delicacy for pepper soup and stews. $15.99 per lb." },
  { slug: "snails", name: "Snails", price: 15.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/snapper.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh snails, prized in African cuisine for their tender texture and rich flavor. Ideal for soups, stews, and grilling.", metaTitle: "Snails - Adom African Market Minneapolis", metaDescription: "Buy fresh snails at Adom African Market in Minneapolis. Tender and flavorful for soups and grilling. $15.99 per lb." },
  { slug: "beef-soup-bone", name: "Beef Soup Bone", price: 7.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/goat.jpg", fallback: "https://placehold.co/400x300/png", description: "Meaty beef soup bones, perfect for making rich, hearty broths and traditional African soups.", metaTitle: "Beef Soup Bone - Adom African Market Minneapolis", metaDescription: "Buy beef soup bones at Adom African Market in Minneapolis. Perfect for rich broths and African soups. $7.99 per lb." },
  { slug: "cow-skin", name: "Cow Skin", price: 7.99, unit: "per lb", category: "meat-seafood", featured: false, image: "/images/goat.jpg", fallback: "https://placehold.co/400x300/png", description: "Cleaned cow skin (ponmo/kpomo), a popular protein in Nigerian and West African soups and stews.", metaTitle: "Cow Skin (Ponmo) - Adom African Market Minneapolis", metaDescription: "Buy cow skin (ponmo) at Adom African Market in Minneapolis. Popular protein for Nigerian soups and stews. $7.99 per lb." },

  { slug: "ayaba-palm-oil", name: "Ayaba Palm Oil", price: 8.99, unit: "bottle", category: "oils-cooking", featured: true, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png", description: "Premium Ayaba brand palm oil, rich in color and flavor. Essential for authentic West African soups and stews.", metaTitle: "Ayaba Palm Oil - Adom African Market Minneapolis", metaDescription: "Buy Ayaba Palm Oil at Adom African Market in Minneapolis. Premium quality for authentic African cooking. $8.99 per bottle." },
  { slug: "vahnos-oil-500ml", name: "Vahnos Oil 500ml", price: 5.99, unit: "bottle", category: "oils-cooking", featured: true, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png", description: "Vahnos cooking oil in a convenient 500ml bottle. Versatile oil for everyday African cooking needs.", metaTitle: "Vahnos Oil 500ml - Adom African Market Minneapolis", metaDescription: "Buy Vahnos Oil 500ml at Adom African Market in Minneapolis. Versatile cooking oil for everyday use. $5.99." },
  { slug: "vahnos-oil-2l", name: "Vahnos Oil 2L", price: 15.99, unit: "bottle", category: "oils-cooking", featured: true, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png", description: "Vahnos cooking oil in a 2-liter bottle. Great value for families who cook African dishes regularly.", metaTitle: "Vahnos Oil 2L - Adom African Market Minneapolis", metaDescription: "Buy Vahnos Oil 2L at Adom African Market in Minneapolis. Family-size value for regular cooking. $15.99." },
  { slug: "vahnos-oil-4-5l", name: "Vahnos Oil 4.5L", price: 28.99, unit: "bottle", category: "oils-cooking", featured: false, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png", description: "Vahnos cooking oil in a large 4.5-liter bottle. Best value for bulk cooking and large households.", metaTitle: "Vahnos Oil 4.5L - Adom African Market Minneapolis", metaDescription: "Buy Vahnos Oil 4.5L at Adom African Market in Minneapolis. Best bulk value for large households. $28.99." },
  { slug: "nutrolin-oil", name: "Nutrolin Oil", price: 12.99, unit: "bottle", category: "oils-cooking", featured: true, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png", description: "Nutrolin cooking oil, a trusted brand for everyday frying and African cooking. Rich flavor and versatile.", metaTitle: "Nutrolin Oil - Adom African Market Minneapolis", metaDescription: "Buy Nutrolin Oil at Adom African Market in Minneapolis. Trusted cooking oil for everyday use. $12.99." },
  { slug: "ghee-butter", name: "Ghee (Butter)", price: 9.99, unit: "jar", category: "oils-cooking", featured: false, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png", description: "Pure ghee (clarified butter), rich and aromatic. Perfect for traditional African and South Asian cooking.", metaTitle: "Ghee Butter - Adom African Market Minneapolis", metaDescription: "Buy ghee (clarified butter) at Adom African Market in Minneapolis. Rich and aromatic for cooking. $9.99." },

  { slug: "parboiled-rice-25lb", name: "Parboiled Rice (25 lb bag)", price: 19.99, unit: "each", category: "rice-grains", featured: true, image: "/images/grains.jpg", fallback: "https://placehold.co/400x300/png", description: "25-pound bag of premium parboiled rice. A pantry staple for jollof rice, fried rice, and everyday meals.", metaTitle: "Parboiled Rice 25 lb - Adom African Market Minneapolis", metaDescription: "Buy 25 lb parboiled rice at Adom African Market in Minneapolis. Perfect for jollof and everyday meals. $19.99." },
  { slug: "jasmine-rice-25lb", name: "Jasmine Rice (25 lb bag)", price: 25.99, unit: "each", category: "rice-grains", featured: true, image: "/images/grains.jpg", fallback: "https://placehold.co/400x300/png", description: "25-pound bag of fragrant jasmine rice. Aromatic and fluffy, perfect for pairing with African stews and curries.", metaTitle: "Jasmine Rice 25 lb - Adom African Market Minneapolis", metaDescription: "Buy 25 lb jasmine rice at Adom African Market in Minneapolis. Fragrant and fluffy for stews and curries. $25.99." },
  { slug: "jasmine-rice-35lb", name: "Jasmine Rice (35 lb bag)", price: 39.99, unit: "each", category: "rice-grains", featured: true, image: "/images/grains.jpg", fallback: "https://placehold.co/400x300/png", description: "35-pound bag of fragrant jasmine rice. Best value for large families and bulk buyers.", metaTitle: "Jasmine Rice 35 lb - Adom African Market Minneapolis", metaDescription: "Buy 35 lb jasmine rice at Adom African Market in Minneapolis. Best bulk value for large families. $39.99." },
  { slug: "ijebu-garri", name: "Ijebu Garri", price: 15.99, unit: "bag", category: "rice-grains", featured: true, image: "/images/cassava.jpg", fallback: "https://placehold.co/400x300/png", description: "Premium Ijebu garri, a crispy cassava flour staple. Enjoy as a snack with groundnuts or as eba with soup.", metaTitle: "Ijebu Garri - Adom African Market Minneapolis", metaDescription: "Buy Ijebu Garri at Adom African Market in Minneapolis. Premium cassava flour for snacking or eba. $15.99." },

  { slug: "tea-bread", name: "Tea Bread", price: 6.99, unit: "each", category: "pantry-packaged", subcategory: "bread", featured: true, image: "/images/bread.jpg", fallback: "https://placehold.co/400x300/png", description: "Classic tea bread, soft and lightly sweet. Perfect for breakfast or as a snack with tea.", metaTitle: "Tea Bread - Adom African Market Minneapolis", metaDescription: "Buy tea bread at Adom African Market in Minneapolis. Soft, lightly sweet bread for breakfast. $6.99." },
  { slug: "hill-bread", name: "Hill Bread", price: 6.99, unit: "each", category: "pantry-packaged", subcategory: "bread", featured: false, image: "/images/bread.jpg", fallback: "https://placehold.co/400x300/png", description: "Hill bread, a popular West African bread with a soft, fluffy texture. Great for sandwiches or on its own.", metaTitle: "Hill Bread - Adom African Market Minneapolis", metaDescription: "Buy Hill bread at Adom African Market in Minneapolis. Soft, fluffy bread for any meal. $6.99." },
  { slug: "sweet-bread", name: "Sweet Bread", price: 6.99, unit: "each", category: "pantry-packaged", subcategory: "bread", featured: false, image: "/images/bread.jpg", fallback: "https://placehold.co/400x300/png", description: "Sweet bread with a rich, slightly sweet flavor. A favorite for breakfast and snacking.", metaTitle: "Sweet Bread - Adom African Market Minneapolis", metaDescription: "Buy sweet bread at Adom African Market in Minneapolis. Rich, sweet flavor for breakfast. $6.99." },
  { slug: "butter-bread", name: "Butter Bread", price: 7.99, unit: "each", category: "pantry-packaged", subcategory: "bread", featured: false, image: "/images/bread.jpg", fallback: "https://placehold.co/400x300/png", description: "Buttery soft bread, rich and indulgent. Perfect toasted or as a side with soups and stews.", metaTitle: "Butter Bread - Adom African Market Minneapolis", metaDescription: "Buy butter bread at Adom African Market in Minneapolis. Rich, buttery soft bread. $7.99." },
  { slug: "digestive-cookies", name: "Digestive Cookies", price: 4.99, unit: "pack", category: "pantry-packaged", subcategory: "cookies-crackers", featured: true, image: "/images/cookies.jpg", fallback: "https://placehold.co/400x300/png", description: "Classic digestive cookies, lightly sweet and perfect with tea or coffee.", metaTitle: "Digestive Cookies - Adom African Market Minneapolis", metaDescription: "Buy digestive cookies at Adom African Market in Minneapolis. Classic cookies for tea time. $4.99." },
  { slug: "jacob-crackers", name: "Jacob Crackers", price: 7.99, unit: "pack", category: "pantry-packaged", subcategory: "cookies-crackers", featured: false, image: "/images/cookies.jpg", fallback: "https://placehold.co/400x300/png", description: "Jacob crackers, a crunchy and savory snack. Great on their own or with cheese and spreads.", metaTitle: "Jacob Crackers - Adom African Market Minneapolis", metaDescription: "Buy Jacob crackers at Adom African Market in Minneapolis. Crunchy, savory snack crackers. $7.99." },
  { slug: "shortbread", name: "Shortbread", price: 4.99, unit: "pack", category: "pantry-packaged", subcategory: "cookies-crackers", featured: false, image: "/images/cookies.jpg", fallback: "https://placehold.co/400x300/png", description: "Buttery shortbread cookies, rich and crumbly. A timeless treat with tea.", metaTitle: "Shortbread - Adom African Market Minneapolis", metaDescription: "Buy shortbread cookies at Adom African Market in Minneapolis. Buttery and crumbly. $4.99." },
  { slug: "oven-ten-cookies", name: "Oven Ten Cookies", price: 2.99, unit: "pack", category: "pantry-packaged", subcategory: "cookies-crackers", featured: false, image: "/images/cookies.jpg", fallback: "https://placehold.co/400x300/png", description: "Oven Ten cookies, a popular affordable snack. Crunchy and delicious for any occasion.", metaTitle: "Oven Ten Cookies - Adom African Market Minneapolis", metaDescription: "Buy Oven Ten cookies at Adom African Market in Minneapolis. Affordable crunchy snack. $2.99." },
  { slug: "chin-chin", name: "Chin Chin", price: 2.50, unit: "bag", category: "pantry-packaged", subcategory: "snacks", featured: true, image: "/images/snacks.jpg", fallback: "https://placehold.co/400x300/png", description: "Crunchy chin chin, a beloved West African fried dough snack. Sweet, crispy, and addictive.", metaTitle: "Chin Chin - Adom African Market Minneapolis", metaDescription: "Buy chin chin at Adom African Market in Minneapolis. Crunchy West African fried dough snack. $2.50." },
  { slug: "plantain-chips-snack", name: "Plantain Chips", price: 5.99, unit: "bag", category: "pantry-packaged", subcategory: "snacks", featured: false, image: "/images/plantain.jpg", fallback: "https://placehold.co/400x300/png", description: "Crispy plantain chips, lightly salted. A delicious and healthy alternative to potato chips.", metaTitle: "Plantain Chips - Adom African Market Minneapolis", metaDescription: "Buy plantain chips at Adom African Market in Minneapolis. Crispy, lightly salted snack. $5.99." },
  { slug: "dahi-yogurt", name: "Dahi (Yogurt)", price: 4.99, unit: "each", category: "pantry-packaged", subcategory: "snacks", featured: false, image: "/images/snacks.jpg", fallback: "https://placehold.co/400x300/png", description: "Fresh dahi (yogurt), creamy and tangy. Enjoy as a snack, drink, or side dish.", metaTitle: "Dahi Yogurt - Adom African Market Minneapolis", metaDescription: "Buy dahi (yogurt) at Adom African Market in Minneapolis. Creamy and tangy. $4.99." },
  { slug: "bissap-hibiscus", name: "Bissap (Hibiscus)", price: 5.99, unit: "each", category: "pantry-packaged", subcategory: "beverages", featured: true, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Bissap (hibiscus) drink, a refreshing West African favorite. Tart, sweet, and full of antioxidants.", metaTitle: "Bissap Hibiscus Drink - Adom African Market Minneapolis", metaDescription: "Buy bissap (hibiscus) drink at Adom African Market in Minneapolis. Refreshing and healthy. $5.99." },
  { slug: "peat-malt-bottle", name: "Peat Malt (Bottle)", price: 17.99, unit: "each", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Peat malt drink in bottle form. A rich, non-alcoholic malt beverage popular across Africa.", metaTitle: "Peat Malt Bottle - Adom African Market Minneapolis", metaDescription: "Buy Peat Malt bottle at Adom African Market in Minneapolis. Rich non-alcoholic malt drink. $17.99." },
  { slug: "malta-guinness-small", name: "Malta Guinness (Small Pack)", price: 5.99, unit: "pack", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Malta Guinness small pack, a sweet non-alcoholic malt drink. Refreshing and energizing.", metaTitle: "Malta Guinness Small Pack - Adom African Market Minneapolis", metaDescription: "Buy Malta Guinness small pack at Adom African Market in Minneapolis. Sweet malt drink. $5.99." },
  { slug: "malta-guinness-case", name: "Malta Guinness (Case)", price: 15.00, unit: "case", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Malta Guinness case, great value for malt drink lovers. Stock up for the family.", metaTitle: "Malta Guinness Case - Adom African Market Minneapolis", metaDescription: "Buy Malta Guinness case at Adom African Market in Minneapolis. Great value bulk pack. $15.00." },
  { slug: "malta-guinness-carton", name: "Malta Guinness (Whole Carton)", price: 28.99, unit: "carton", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Malta Guinness whole carton, the best bulk value. Perfect for events and large households.", metaTitle: "Malta Guinness Whole Carton - Adom African Market Minneapolis", metaDescription: "Buy Malta Guinness whole carton at Adom African Market in Minneapolis. Best bulk value. $28.99." },
  { slug: "milo", name: "Milo", price: 30.00, unit: "each", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Milo chocolate malt drink mix. A beloved African staple for hot or cold beverages.", metaTitle: "Milo - Adom African Market Minneapolis", metaDescription: "Buy Milo at Adom African Market in Minneapolis. Chocolate malt drink mix. $30.00." },
  { slug: "club", name: "Club", price: 2.99, unit: "each", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Club soft drink, a refreshing carbonated beverage popular across West Africa.", metaTitle: "Club Drink - Adom African Market Minneapolis", metaDescription: "Buy Club drink at Adom African Market in Minneapolis. Refreshing carbonated beverage. $2.99." },
  { slug: "zobo-jackobug", name: "Zobo (Jackobug)", price: 0, unit: "each", category: "pantry-packaged", subcategory: "beverages", featured: false, image: "/images/drinks.jpg", fallback: "https://placehold.co/400x300/png", description: "Zobo (Jackobug) drink, a traditional West African herbal beverage. Price to be determined.", metaTitle: "Zobo Jackobug - Adom African Market Minneapolis", metaDescription: "Buy Zobo (Jackobug) at Adom African Market in Minneapolis. Traditional herbal beverage." },

  { slug: "shrimp-powder", name: "Shrimp Powder", price: 7.99, unit: "each", category: "spices-seasoning", featured: true, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png", description: "Shrimp powder, a key seasoning in West African cooking. Adds rich umami flavor to soups, stews, and rice dishes.", metaTitle: "Shrimp Powder - Adom African Market Minneapolis", metaDescription: "Buy shrimp powder at Adom African Market in Minneapolis. Rich umami seasoning for soups and stews. $7.99." },
  { slug: "alligator-pepper", name: "Alligator Pepper", price: 9.99, unit: "each", category: "spices-seasoning", featured: true, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png", description: "Alligator pepper, a traditional West African spice with a warm, peppery flavor. Used in ceremonies, cooking, and traditional medicine.", metaTitle: "Alligator Pepper - Adom African Market Minneapolis", metaDescription: "Buy alligator pepper at Adom African Market in Minneapolis. Traditional West African spice. $9.99." },
  { slug: "njansan", name: "Njansan", price: 3.99, unit: "each", category: "spices-seasoning", featured: true, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png", description: "Njansan seeds, a unique Cameroonian spice with a nutty, aromatic flavor. Essential for traditional Cameroonian dishes.", metaTitle: "Njansan - Adom African Market Minneapolis", metaDescription: "Buy njansan at Adom African Market in Minneapolis. Unique Cameroonian spice. $3.99." },
  { slug: "nido", name: "Nido", price: 80.00, unit: "each", category: "spices-seasoning", featured: true, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png", description: "Nido powdered milk, a household staple across Africa. Rich, creamy, and perfect for beverages, baking, and cooking.", metaTitle: "Nido - Adom African Market Minneapolis", metaDescription: "Buy Nido powdered milk at Adom African Market in Minneapolis. Household staple for beverages and cooking. $80.00." },
  { slug: "onugbu", name: "Onugbu", price: 35.00, unit: "each", category: "spices-seasoning", featured: false, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png", description: "Onugbu (bitter leaf), dried and ready for use in traditional Nigerian soups like ofe onugbu. Rich in nutrients.", metaTitle: "Onugbu - Adom African Market Minneapolis", metaDescription: "Buy onugbu (bitter leaf) at Adom African Market in Minneapolis. For traditional Nigerian soups. $35.00." },
  { slug: "conga-sachet", name: "Conga Sachet", price: 35.00, unit: "each", category: "spices-seasoning", featured: false, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png", description: "Conga sachet seasoning, a popular West African flavor enhancer. Adds depth and richness to any dish.", metaTitle: "Conga Sachet - Adom African Market Minneapolis", metaDescription: "Buy Conga sachet at Adom African Market in Minneapolis. Popular West African seasoning. $35.00." },
]

export function getProductBySlug(slug: string): Product | undefined {
  return allProducts.find((p) => p.slug === slug)
}

export function getProductsByCategory(category: Product["category"]): Product[] {
  return allProducts.filter((p) => p.category === category)
}

export function getFeaturedByCategory(category: Product["category"]): Product[] {
  return allProducts.filter((p) => p.category === category && p.featured)
}

export function getProductsBySubcategory(subcategory: string): Product[] {
  return allProducts.filter((p) => p.subcategory === subcategory)
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase().trim()
  if (!q) return []
  return allProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.category.replace("-", " ").includes(q) ||
      (p.subcategory && p.subcategory.replace("-", " ").includes(q))
  )
}

export const categories = [
  { name: "Oils & Cooking", slug: "oils-cooking", image: "/images/palm-oil.jpg" },
  { name: "Fresh Produce", slug: "fresh-produce", image: "/images/plantain.jpg" },
  { name: "Fresh Meat & Seafood", slug: "meat-seafood", image: "/images/snapper.jpg" },
  { name: "Rice & Grains", slug: "rice-grains", image: "/images/grains.jpg" },
  { name: "Pantry / Packaged Foods", slug: "pantry-packaged", image: "/images/cookies.jpg" },
  { name: "Spices & Seasoning", slug: "spices-seasoning", image: "/images/spices.jpg" },
]

export const products = [
  { name: "Jollof Rice Seasoning", price: 8.99, image: "/images/spices.jpg", fallback: "https://placehold.co/400x300/png" },
  { name: "Plantain Chips", price: 5.99, image: "/images/plantain.jpg", fallback: "https://placehold.co/400x300/png" },
  { name: "Palm Oil (1L)", price: 12.99, image: "/images/palm-oil.jpg", fallback: "https://placehold.co/400x300/png" },
  { name: "Garri (Fine)", price: 9.99, image: "/images/cassava.jpg", fallback: "https://placehold.co/400x300/png" },
  { name: "Suya Spice Mix", price: 6.99, image: "/images/suya.jpg", fallback: "https://placehold.co/400x300/png" },
  { name: "Dried Beans (2lb)", price: 7.99, image: "/images/beans.jpg", fallback: "https://placehold.co/400x300/png" },
]

export const menuItems = [
  { name: "Fufu Flour Mix", desc: "Pounded yam, cassava, and plantain varieties", price: 8.99, image: "/images/fufu.jpg" },
  { name: "Egusi Seeds (Ground)", desc: "Premium melon seeds for traditional soups", price: 10.99, image: "/images/grains.jpg" },
  { name: "Dried Stockfish", desc: "Authentic smoked fish for rich, flavorful stews", price: 15.99, image: "/images/suya.jpg" },
  { name: "Shea Butter (Raw)", desc: "Unrefined, natural shea butter from West Africa", price: 12.99, image: "/images/palm-oil.jpg" },
  { name: "Yam Flour (Amala)", desc: "Finely milled yam flour for smooth amala", price: 9.99, image: "/images/yam.jpg" },
  { name: "Ogbono Seeds", desc: "Wild mango seeds for thick, draw soups", price: 14.99, image: "/images/spices.jpg" },
]

export const testimonials = [
  { name: "Amara Okafor", role: "Regular Customer", text: "Adom African Market is my go-to store for authentic African groceries. The quality of their products is unmatched, and the staff is always so welcoming and helpful." },
  { name: "Kwame Mensah", role: "Chef", text: "As a professional chef specializing in West African cuisine, I rely on Adom for the freshest ingredients. Their palm oil and spices are top quality every single time." },
  { name: "Fatima Diallo", role: "Food Blogger", text: "I\'ve tried many African grocery stores, but Adom stands out for their wide selection and authentic products. It feels like shopping back home in Dakar!" },
  { name: "David Adeyemi", role: "Customer", text: "The best place to find Nigerian ingredients in the area. From garri to ogbono, they have everything I need for my family\'s traditional meals." },
]

export const blogPosts = [
  { title: "How to Make the Perfect Jollof Rice at Home", date: "February 15, 2026", category: "Recipes", image: "/images/jollof.jpg" },
  { title: "Essential African Spices Every Kitchen Needs", date: "February 10, 2026", category: "Guide", image: "/images/spices.jpg" },
  { title: "The Health Benefits of Traditional African Foods", date: "February 5, 2026", category: "Wellness", image: "/images/about.jpg" },
]
